version: '3'
services:

  analyze_thread:
    build: ./analyze
    expose:
      - "6000"
    depends_on:
      - record_thread
      - redis
      - postgres
    links:
      - postgres

  record_thread:
    build: ./record
    # devices:
    #   - /dev/video0:/dev/video0
    #   - /dev/video1:/dev/video1
    expose:
      - "7000"
    depends_on:
      - redis
      - postgres

  tornado_monitor:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
      - analyze_thread
      - record_thread
    links:
      - redis
      - postgres

  redis:
    image: redis
    expose:
      - "6379"

  postgres:
    image: postgres
    expose:
      - "5432"
    env_file:
      - secret.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: