version: '3'
services:

  analyze_thread:
    build: ./analyze
    expose:
      - "6000"
    depends_on:
      - record_thread
      - redis
      - postgres
    links:
      - postgres

  record_thread:
    build: ./record
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    expose:
      - "7000"
    depends_on:
      - redis
      - postgres

  tornado_monitor:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
      - analyze_thread
      - record_thread
    links:
      - redis
      - postgres

  redis:
    image: redis
    expose:
      - "6379"
    # ports:
      # - "6379:6379"

  postgres:
    # restart: always
    image: postgres
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: "tornado"
      POSTGRES_PASSWORD: "ttasw1234"
      POSTGRES_DB: "tornado_dev"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - tornado_monitor
    volumes:
      - ./static:/static

volumes:
  pgdata: